version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    working_dir: /app
    environment:
      - SHARED_DIR=/shared
      - APP_HOST=localhost
      - APP_SECRET_KEY_BASE="m9uyofMZTKL76t+FzUfc8d6XnNAKpCYhNcBdinFRsYkXQ+g3vst/BJF9yFfUoQnW"
    volumes:
      - .:/app:delegated
      - ~/.ssh:/root/.ssh:cached
      - shared_vol:/shared
    ports:
      - "4000:4000"
    command: mix phx.server
  frontend:
    image: node:14.12.0
    working_dir: /app/assets
    volumes:
      - .:/app:delegated
      - shared_vol:/shared
    ports:
      - "3000:3000"
    entrypoint: ""
    command: yarn start
    tty: true # The server stops on EOF
  infrastructure:
    build:
      context: .
      dockerfile: Dockerfile.infrastructure
    working_dir: /app/infrastructure
    volumes:
      - .:/app:delegated
      - ~/.ssh:/root/.ssh:cached
      - ~/.aws:/root/.aws
    entrypoint:
      ["/bin/bash", "-c", "eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa && /bin/bash"]
volumes:
  shared_vol:
