FROM node:14.12.0

ADD ./assets /app
WORKDIR /app

RUN npm install

RUN npm run build

FROM elixir:1.10.4

ARG APP_VERSION

# Install hex
RUN mix local.hex --force

# Install rebar
RUN mix local.rebar --force

# Add app
ADD . /app
WORKDIR /app

# Install deps
RUN mix deps.get --only production

# Build release
ENV MIX_ENV production
ENV VERSION $APP_VERSION

RUN mix release lock_the_lock

ENTRYPOINT ["/app/_build/rel/lock_the_lock/bin/lock_the_lock", "start"]
