version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    working_dir: /app
    environment:
      - SHARED_DIR=/shared
      - LOCK_SECRET=893e83fa0013385664d7c3346cecc34b
    volumes:
      - .:/app:delegated
      - ~/.ssh:/root/.ssh:cached
      - shared_vol:/shared
    ports:
      - "4000:4000"
    command: mix phx.server
  frontend:
    image: node:14.12.0
    working_dir: /app/assets
    volumes:
      - .:/app:delegated
      - shared_vol:/shared
    ports:
      - "3000:3000"
    entrypoint: ""
    command: yarn start
    tty: true # The server stops on EOF
volumes:
  shared_vol:
