name: Building and pushing a docker image to Amazon ECR

on:
  pull_request:
    paths:
    - lib/**
    - assets/**
    - Dockerfile.release
    - mix.exs
    - .github/**
    branches:
    - master
  push:
    paths:
    - lib/**
    - assets/**
    - Dockerfile.release
    - mix.exs
    - .github/**
    branches:
    - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        uses: actions/checkout@master
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
      - id: step2
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.6
        with:
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.step2.outputs.new_tag }}
      ecr_image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/lock-the-lock:${{ steps.step2.outputs.new_tag }}
  build-and-push:
    needs: tag
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - name: Build and tag the image
      run: |
        docker build \
          -t lock-the-lock:${{ needs.tag.outputs.new_tag }} \
          -t ${{ needs.tag.outputs.ecr_image }} \
          -f Dockerfile.release \
          --build-arg APP_VERSION=${{ needs.tag.outputs.new_tag }} \
          .

    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ${{ needs.tag.outputs.ecr_image }}
